### ISSUE TITLE
This role should be tested

### ISSUE THREAD

**Issue by odyssey4me** [rcbops/openstack-ops#20]
In order to prevent patches from merging that are incomplete, this role should have a deployment test.

**Comment by odyssey4me** [comment]
If you do a PR to https://github.com/rcbops/rpc-gating/blob/master/rpc_jobs/irr_role_test.yml to add:

```
    repo:
      # IRR REPOS ARE ADDED HERE
      - rpc_support:
          irr_repo_url: https://github.com/rsoprivatecloud/openstack-ops
```

Then that should do the trick. There might need to be some additional stuff to enable webhooks. Join the #rpc-gating slack channel for further guidance once the initial PR is up.
